CREATE TABLE IF NOT EXISTS post
(
    id INT AUTO_INCREMENT PRIMARY KEY NOT NULL ,
    content VARCHAR(50) NOT NULL ,
    startTime TIME NOT NULL ,
    finishTime TIME NOT NULL,
    posts VARCHAR(200) NOT NULL
 )